drop table if exists cohorts;

create table cohorts (
    id bigint generated by default as identity primary key,
    name text not null unique,
    github text not null,
    dates text,
    num_people integer
);

insert into
    cohorts (name, github, dates, num_people)
values
    ('FAC21', 'fac21', 'March-June 2021', 16);

DROP table if exists people;

create table people (
    id bigint generated by default as identity primary key,
    user_id uuid unique,
    name text not null,
    github text not null,
    cohort text references cohorts(name) not null,
    bio text,
    socials json
);

insert into
    people (name, github, cohort, bio, socials)
values
    (
        'Jo Humphrey',
        'jamdelion',
        'FAC21',
        'Jo has a bio, it is this',
        { 'hashnode': 'jo',
        'linkedin': 'jo-humphrey' }
    ),
    (
        'Safia Ali',
        'fi-ya',
        'FAC21',
        'Safia has a bio, it is this',
        null
    );

ALTER TABLE ONLY public.people
ADD CONSTRAINT people_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
