import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { supabase } from "../database/supabaseClient";
import FacesLine from "../components/FacesLine";
// import Login from "../components/Login";
import Auth from "../components/Auth";
// import Signup from "../components/SignUp";
import redirect from "nextjs-redirect"
// import Header from "../components/Header";

export default function Home({ session }) {

  const Redirect = redirect('/main')

  return (
    <div className={styles.container}>
      <Head>
        <title>FAC Directory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>FAC Directory</h1>

        {!session ? (
          <Auth/>
        ) :
        (
          <Redirect>
            <p>Logging you in...</p>
          </Redirect>
        )}
        
        </main>

      <footer className={styles.footer}>
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  );
}
